"""Moodle GIFT renderer. Pure functions: Question objects in, GIFT text out.

Escaping (the whole point of rendering in code rather than asking the model
for GIFT directly): inside any field, backslash and the six GIFT control
characters ~ = # { } : must be backslash-escaped, backslash itself first.
Fields are single-line by construction (questions.py collapses whitespace);
questions are separated by a mandatory blank line; file is UTF-8.
"""

from __future__ import annotations

from .questions import Question

_CONTROL = "~=#{}:"


def escape_gift(text: str) -> str:
    text = text.replace("\\", "\\\\")
    for ch in _CONTROL:
        text = text.replace(ch, "\\" + ch)
    return text


def render_question(q: Question, session_id: int | str | None, number: int) -> str:
    prefix = f"S{session_id}-" if session_id is not None else ""
    title = escape_gift(f"{prefix}Q{number:02d} {q.name}")
    stem = escape_gift(q.stem)
    feedback = f"####{escape_gift(q.feedback)}" if q.feedback else ""

    if q.qtype == "truefalse":
        value = "TRUE" if q.answer else "FALSE"
        return f"::{title}::{stem} {{{value}{feedback}}}"

    lines = [f"::{title}::{stem} {{"]
    for i, option in enumerate(q.options or ()):
        marker = "=" if i == q.correct_index else "~"
        lines.append(f"{marker}{escape_gift(option)}")
    if feedback:
        lines.append(feedback)
    lines.append("}")
    return "\n".join(lines)


def render_gift(
    questions: list[Question],
    *,
    course_code: str,
    session_id: int | str | None,
    session_date: str,
    model: str,
    category_header: bool = True,
) -> str:
    session_txt = f" session {session_id}" if session_id is not None else ""
    blocks = [f"// {course_code}{session_txt} ({session_date}) — generated by TSCT run_qcm, model {model}"]
    if category_header:
        category = f"{course_code} {session_date}" + (f" S{session_id}" if session_id is not None else "")
        blocks.append(f"$CATEGORY: $course$/top/{escape_gift(category)}")
    for number, q in enumerate(questions, start=1):
        blocks.append(render_question(q, session_id, number))
    return "\n\n".join(blocks) + "\n"
