// Moodle GIFT renderer — JS port of scripts/lib/gift.py. Pure functions:
// question objects in, GIFT text out. Must stay byte-identical to the Python
// renderer (validated against the shared golden fixture).

const CONTROL = "~=#{}:";

export function escapeGift(text) {
  text = text.replaceAll("\\", "\\\\");
  for (const ch of CONTROL) text = text.replaceAll(ch, "\\" + ch);
  return text;
}

export function renderQuestion(q, sessionId, number) {
  const prefix = sessionId !== null && sessionId !== undefined ? `S${sessionId}-` : "";
  const title = escapeGift(`${prefix}Q${String(number).padStart(2, "0")} ${q.name}`);
  const stem = escapeGift(q.stem);
  const feedback = q.feedback ? `####${escapeGift(q.feedback)}` : "";

  if (q.qtype === "truefalse") {
    const value = q.answer ? "TRUE" : "FALSE";
    return `::${title}::${stem} {${value}${feedback}}`;
  }

  const lines = [`::${title}::${stem} {`];
  (q.options || []).forEach((option, i) => {
    lines.push(`${i === q.correctIndex ? "=" : "~"}${escapeGift(option)}`);
  });
  if (feedback) lines.push(feedback);
  lines.push("}");
  return lines.join("\n");
}

export function renderGift(questions, { courseCode, sessionId = null, sessionDate, model, categoryHeader = true }) {
  const sessionTxt = sessionId !== null && sessionId !== undefined ? ` session ${sessionId}` : "";
  const blocks = [`// ${courseCode}${sessionTxt} (${sessionDate}) — generated by TSCT run_qcm, model ${model}`];
  if (categoryHeader) {
    const category = `${courseCode} ${sessionDate}` + (sessionId !== null && sessionId !== undefined ? ` S${sessionId}` : "");
    blocks.push(`$CATEGORY: $course$/top/${escapeGift(category)}`);
  }
  questions.forEach((q, i) => blocks.push(renderQuestion(q, sessionId, i + 1)));
  return blocks.join("\n\n") + "\n";
}
